#!/usr/bin/env python3
"""
Embed the agent-layer validation module into the tool's single HTML file (Build Brief Step 3).

IDENTICAL COPY in both repos (hash-locked by LOCK.sha256).  Reads:
    validation.js                       the shared module
    config.json                         {tool, html, paymentLabel}  (per tool)
    ../schemas/*.json                   engine inputs / drafts / outputs / unresolved policy (Step 2)
and writes ONE block into the tool HTML, immediately before the final </body>:

    <!-- AGENT-LAYER:BEGIN ... --> <script id="agent-layer"> ... </script> <!-- AGENT-LAYER:END -->

The block is purely additive: it defines window.AgentLayer and nothing else, references no existing function or
element, and does nothing until something calls it. The tool behaves identically with it present.

    python agent-layer/embed.py            # (re)generate the block in place
    python agent-layer/embed.py --check    # exit 1 if the block in the HTML is stale or hand-edited
    python agent-layer/embed.py --remove   # take the block out again (rollback helper)
"""
import hashlib
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BEGIN_RE = re.compile(r"<!-- AGENT-LAYER:BEGIN[^>]*-->")
END = "<!-- AGENT-LAYER:END -->"


def read(path):
    with io.open(path, encoding="utf-8", newline=None) as f:   # universal newlines -> '\n'
        return f.read()


def js_json(obj):
    """JSON safe to place inside a <script> element: '</' can never terminate the script."""
    return json.dumps(obj, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/").replace("<!--", "<\\!--")


def build_block(cfg):
    schemas = {}
    for key, fname in (("inputs", "engine-inputs.schema.json"), ("drafts", "agent-drafts.schema.json"),
                       ("outputs", "engine-outputs.schema.json"), ("policy", "unresolved-policy.json")):
        with io.open(os.path.join(HERE, "..", "schemas", fname), encoding="utf-8") as f:
            schemas[key] = json.load(f)
    module = read(os.path.join(HERE, "validation.js")).rstrip()
    assert "</script" not in module.lower(), "validation.js must not contain a script terminator"
    assert "AGENT-LAYER:" not in module, "validation.js must not contain the block marker text"
    version = re.search(r"var VERSION = '([^']+)'", module).group(1)
    payload = js_json({"tool": cfg["tool"], "paymentLabel": cfg["paymentLabel"], "schemas": schemas})
    nl = "\n"
    return (f"<!-- AGENT-LAYER:BEGIN v{version} (generated by agent-layer/embed.py; do not edit by hand) -->{nl}"
            f'<script id="agent-layer">{nl}{module}{nl}'
            f";(function(){{ try {{ window.AgentLayer.configure({payload}); }} "
            f"catch (e) {{ if (window.console) console.error('AgentLayer configuration failed', e); }} }})();{nl}"
            f"</script>{nl}{END}{nl}")


def main(argv):
    cfg = json.load(io.open(os.path.join(HERE, "config.json"), encoding="utf-8"))
    html_path = os.path.normpath(os.path.join(HERE, cfg["html"]))
    html = read(html_path)
    m = BEGIN_RE.search(html)
    has_block = m is not None
    if "--remove" in argv:
        if has_block:
            end = html.rindex(END) + len(END)
            html = html[: m.start()] + html[end:].lstrip("\n")
            io.open(html_path, "w", encoding="utf-8", newline="\n").write(html)
        print("removed agent-layer block" if has_block else "no block present")
        return 0
    block = build_block(cfg)
    if has_block:
        end = html.rindex(END) + len(END)
        current = html[m.start(): end] + "\n"
        new_html = html[: m.start()] + block + html[end:].lstrip("\n")
    else:
        idx = html.rfind("</body>")
        assert idx > 0, "no </body> found"
        current = None
        new_html = html[:idx] + block + html[idx:]
    if "--check" in argv:
        ok = has_block and current == block
        print("agent-layer block is up to date" if ok else "agent-layer block is MISSING or STALE (run embed.py)")
        return 0 if ok else 1
    io.open(html_path, "w", encoding="utf-8", newline="\n").write(new_html)
    print(f"embedded agent layer into {os.path.basename(html_path)} ({len(block)//1024} KB block)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
