#!/usr/bin/env node
/*
 * HTML-SINK AUDIT (Master Plan workstream Q4b / security plan) - identical logic in both repos; per-tool file (not hash-locked).
 *
 *   node agent-layer/tests/sink_audit.js [--report]
 *
 * Static, heuristic scan of the TOOL's own code (the embedded agent-layer block is excluded) for places where text is written into the page as
 * HTML (`.innerHTML =`, `+=`, insertAdjacentHTML) and for dynamic-code features (eval, new Function). For each HTML sink it classifies:
 *   static       no interpolation -> no injection risk
 *   escaped      interpolates values but calls an escape helper in the same statement
 *   interpolated interpolates values with no escape helper in the statement -> if any value is user-typed, imported or fetched text, it can inject markup
 * It cannot prove a sink is exploitable (some interpolated values are numbers or tool-controlled constants) - it produces the REVIEW LIST.
 * A measurement: it never fails the build. Nothing here changes the tool.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..', '..');
const cfg = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'config.json'), 'utf8'));
const html = fs.readFileSync(path.resolve(__dirname, '..', cfg.html), 'utf8').replace(/\r\n/g, '\n');
const cut = html.indexOf('<!-- AGENT-LAYER:BEGIN');
const src = cut === -1 ? html : html.slice(0, cut);
const ESC = /\b(esc\w*|escape\w*|escHtml|sanitize\w*|DOMPurify)\s*\(/;
const lineOf = (i) => src.slice(0, i).split('\n').length;

/** Read one statement starting at index i: stops at ';' outside strings / template literals (nested ${} handled by depth). */
function statementAt(i) {
  let q = null, depthT = [], j = i;
  for (; j < src.length && j - i < 6000; j++) {
    const ch = src[j], prev = src[j - 1];
    if (q) {
      if (ch === '\\') { j++; continue; }
      if (q === '`') {
        if (ch === '$' && src[j + 1] === '{') { depthT.push(1); q = null; j++; continue; }
        if (ch === '`') q = null;
      } else if (ch === q) q = null;
      continue;
    }
    if (depthT.length) { if (ch === '{') depthT[depthT.length - 1]++; else if (ch === '}') { depthT[depthT.length - 1]--; if (depthT[depthT.length - 1] === 0) { depthT.pop(); q = '`'; continue; } } }
    if (ch === '"' || ch === "'" || ch === '`') { q = ch; continue; }
    if (ch === ';' && !depthT.length) return src.slice(i, j + 1);
    if (ch === '\n' && src[j + 1] === '\n' && prev === '\n') break;
  }
  return src.slice(i, j);
}

const sinks = [];
const re = /\.innerHTML\s*(\+?=)(?!=)|insertAdjacentHTML\s*\(/g;
let m;
while ((m = re.exec(src))) {
  const stmt = statementAt(m.index);
  const rhs = stmt.replace(/^[^=(]*[=(]/, '');
  const hasTemplateInterp = /\$\{/.test(rhs);
  const hasConcat = /['"`]\s*\+\s*[A-Za-z_(]|[A-Za-z_)\]]\s*\+\s*['"`]/.test(rhs);
  const interpolates = hasTemplateInterp || hasConcat;
  const kind = !interpolates ? 'static' : ESC.test(stmt) ? 'escaped' : 'interpolated';
  const userish = (rhs.match(/(?:\$\{|\+\s*)\(?\s*[A-Za-z_][\w.\[\]'"]*?\b(description|desc|title|name|notes?|observation|summary|text|comment|mitigation|owner|rationale|reason|label|message|value|shortdesc|diagnosis|resolution|service|group)\b/gi) || []).length;
  sinks.push({ line: lineOf(m.index), kind, userish, snippet: stmt.replace(/\s+/g, ' ').slice(0, 170) });
}
const dyn = [];
const dre = /\beval\s*\(|new Function\s*\(|setTimeout\s*\(\s*['"`]/g;
while ((m = dre.exec(src))) dyn.push({ line: lineOf(m.index), snippet: src.slice(m.index, m.index + 110).replace(/\s+/g, ' ') });

const count = (k) => sinks.filter((s) => s.kind === k).length;
const review = sinks.filter((s) => s.kind === 'interpolated' && s.userish > 0).sort((a, b) => b.userish - a.userish);
console.log(`${cfg.tool.toUpperCase()}: ${sinks.length} HTML sinks - static ${count('static')}, escaped ${count('escaped')}, interpolated-without-escaping ${count('interpolated')} (of which ${review.length} mention user-text-like fields)`);
console.log(`escape helper present: ${/function\s+esc\w*\s*\(/.test(src)}; dynamic-code sites: ${dyn.length}`);

if (process.argv.includes('--report')) {
  const L = [`# HTML-sink audit - ${cfg.tool === 'rm' ? 'Release Management' : 'ITSM Workflow Intelligence'} tool`, '',
    '*Generated by `agent-layer/tests/sink_audit.js` - heuristic static scan; produces a REVIEW LIST, not proof of exploitability. The tool has not been changed.*', '',
    `* HTML sinks (\`.innerHTML =\`, \`+=\`, \`insertAdjacentHTML\`): **${sinks.length}**`, `* Static (no interpolation): ${count('static')}`, `* Interpolate values AND call an escape helper: ${count('escaped')}`,
    `* **Interpolate values with NO escaping: ${count('interpolated')}** (of which **${review.length}** mention fields that typically hold user-typed text)`,
    `* Escape helper defined in the tool: **${/function\s+esc\w*\s*\(/.test(src) ? 'yes' : 'NO'}**`, `* Dynamic-code sites (\`eval\`, \`new Function\`, string \`setTimeout\`): **${dyn.length}**`, '',
    '**Why it matters.** Anything a user types, imports (backup / JSON) or fetches (content layer) that reaches an un-escaped sink can inject markup or script into the page. In a single-user local tool the direct risk is mostly self-inflicted, but it becomes a real exposure when data can be imported or shared (workspace backup and restore, interoperability import, shift-handover files, the assistant\'s own output) and it blocks adopting a strict Content-Security-Policy. The agent layer itself never inserts model text as HTML.', '',
    '## Dynamic-code sites', '', dyn.length ? dyn.map((d) => `* line ${d.line}: \`${d.snippet.replace(/`/g, "'")}\``).join('\n') : '* none', '',
    '## Review list - interpolated, un-escaped, mentions user-text-like fields (top 40)', '', '| Line | Snippet |', '|---|---|',
    ...review.slice(0, 40).map((s) => `| ${s.line} | \`${s.snippet.replace(/\|/g, '/').replace(/`/g, "'")}\` |`), '',
    '## Proposed treatment (needs James\'s sign-off, part of the engine/UI-change workstream)', '',
    '1. Add one small `escHtml` helper where missing and use it for every user-typed or imported value at the sinks above (behaviour-preserving for normal text).',
    '2. Keep trusted, tool-authored hint/guidance HTML (rule hints, content-layer guidance) as HTML - it is authored, not typed.',
    '3. Add an automated test that feeds markup-looking text through every input and asserts it renders as text.', '4. Then enable the Content-Security-Policy planned in Master Plan 7h #11.', ''];
  fs.writeFileSync(path.join(ROOT, 'SINK-AUDIT.md'), L.join('\n'), 'utf8');
  console.log('wrote SINK-AUDIT.md');
}
